### ISSUE TITLE
UI overlapping

### ISSUE THREAD

**Issue by phgz** [Shougo/ddc-ui-inline#2]
**Ubuntu 20.04.5 or MacOS 13.0.1
NVIM v0.9.0-dev-465+ga505c1acc**
See `minimal.txt` file for reproduction with packages and settings.

Using `ddc#custom#patch_global('ui', 'inline')` conflicts with other ui invoked with `ddc#map#manual_complete` (ex: `('file', 'native')`).

<img width="529" alt="Screenshot 2022-12-12 at 2 28 24 AM" src="https://user-images.githubusercontent.com/22773951/206987508-dfc225a1-41be-486d-b96e-505849fa72fe.png">

To reproduce:

1. convert `minimal.txt` to `minimal.lua`
2. `nvim -u minimal.lua`
3. try `./` in insert mode (inline autosuggestion should appear)
4. do `<S-Tab>` to open manual completion
5. Scroll items

Problem disappear when `completeopt` does not contain `noselect` or `noinsert`.

[minimal.txt](https://github.com/Shougo/ddc-ui-inline/files/10205510/minimal.txt)

**Comment by Shougo** [comment]
Reproduced...  Hm

**Comment by Shougo** [comment]
Fixed.

**Comment by phgz** [comment]
Since commit 4b23ca7 on [Shougo/ddc.vim](https://github.com/Shougo/ddc.vim), this glitch is back.

For manual complete, I'm using
`ddc#map#manual_complete(#{ sources: ['file'], ui: 'native'})`.

<img width="446" alt="Screenshot 2023-01-21 at 5 18 07 PM" src="https://user-images.githubusercontent.com/22773951/213889285-5de74fcb-ed58-4839-b706-f0a1dbf1807f.png">

For the reproduction, it is the same as the original, apart from the `ddc#map#manual_complete` call which is now with the new interface.

Is it due to the removal of this line
`await ddc.autoload(denops, "ui", [options.ui]);`
in `denops/ddc/app.ts` file?

**Comment by Shougo** [comment]
Fixed.  Please update `ddc.vim`.

> Is it due to the removal of this line
> await ddc.autoload(denops, "ui", [options.ui]);
> in denops/ddc/app.ts file?

No.

**Comment by phgz** [comment]
Thanks! It is now working as intended :)
