### ISSUE TITLE
Error when displaying inline suggestion

### ISSUE THREAD

**Issue by phgz** [Shougo/ddc-ui-inline#5]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
When typing, following message will trigger:
```
[denops] Failed to handle message 2,invoke,dispatch,ddc,onEvent,TextChangedI Error: 0,function ddc#ui#inline#_show, line 51: Vim(call):E5555: API call: Invalid 'virt_text_pos'
```

## Expected
inline suggestion appearing.

## Environment Information

- ddc.vim version (SHA1): latest

- denops.vim version (SHA1): latest

- deno version(`deno -V` output): v1.33.4

- OS: macOS 13.3.1

- neovim/Vim `:version` output: v0.10.0-dev-382+gebb10d624

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
set completeopt=menu,menuone,noinsert,noselect
call ddc#custom#patch_global('sources', ['around'])
call ddc#custom#patch_global('sourceOptions', #{
	\ _: #{
		\   matchers: ['matcher_fuzzy'],
		\   sorters: ['sorter_fuzzy'],
		\   converters: ['converter_remove_overlap'],
		\   minAutoCompleteLength : 1,
	\     }
	\ })
call ddc#custom#patch_global('backspaceCompletion', 'v:true')
call ddc#custom#patch_global('filterParams', #{
		\   matcher_fuzzy: #{ splitMode: 'word' }
	\ })
call ddc#custom#patch_global('sourceOptions', #{
		\ around: #{mark: 'A'},
	\})
call ddc#custom#patch_global('sourceParams', #{})
call ddc#custom#patch_global('ui', 'inline')

call ddc#enable(#{context_filetype: 'treesitter'})
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start typing 3-4 chars to get a completion.
2. Go back to normal mode.
3. Error triggers.

**Comment by Shougo** [comment]
OK.  I will revert the change...
